name: Manual
on:
  workflow_dispatch: # 手動実行イベント
    inputs:
      greeting: 
        type: choice
        options:
          - Hello
          - Hi
          - Hey
        default: Hello 
        required: true 
        description: interjection
      name: 
        type: string 
        default: World 
        required: true 
        description: name 
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}" "${{ inputs.name }}"
