name: TagEvent
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  # workflow_dispatch
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: dump
        run: echo "${CONTEXT}"
        env:
          CONTEXT: ${{ toJSON(github) }} 
      - name: SHA
        run: echo "${SHA}"
        env:
          SHA: ${{ toJSON(github.event.after) }} 
      - name: label
        run: echo "${LABEL}"
        env:
          LABEL: ${{ toJSON(github.event.label) }}
      - uses: actions/checkout@v4    
      - uses: actions/github-script@v7
        id: log-level
        with:
          script: |
            const script = require('./.github/workflows/scripts/log-level.js');
            await script( context );
          result-encoding: string
      - name: show log level
        run: echo "${{ steps.log-level.outputs.result }}"
