name: TagEvent
on:
  pull_request:
    types: [opened, synchronize, reopened]
  # workflow_dispatch
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: SHA
        run: echo "${{ toJSON(github) }}"
      # - name: PR URL
      #   run: echo ${{ github.server_url }}/${{ github.repository }}/pull/${{ steps.pr.outputs.pull_request_number }}
